server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cosinus_library
    username: postgres
    password: 4743
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    database-platform:
      org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    listener:
      direct:
        consumers-per-queue:


  mail:
    host: smtp.gmail.com
    port: 587
    username: toirovsaidazim84@gmail.com
    password: swimfvdbwqhswkao
    properties:
      mjaail:
        smtp:
          auth: true
      mail:
        smtp:
          starttls:
            enable: true

jwt:
  access:
    token:
      expiry: 3600000 # 60 minutes
      secret:
        key: 8d1877ec5cb495b9cd9993c636a54ee0e7486212232baaa269dd731bb1ccb6ee

  refresh:
    token:
      expiry: 864000000 # 10 days
      secret:
        key:

